-- MySQL Script generated by MySQL Workbench
-- Sat May 16 19:51:30 2020
-- Model: Sakila Full    Version: 2.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Member
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Member` ;

-- -----------------------------------------------------
-- Schema Member
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Member` DEFAULT CHARACTER SET utf8 ;
USE `Member` ;

-- -----------------------------------------------------
-- Table `Member`.`Univeristy`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Member`.`Univeristy` ;

CREATE TABLE IF NOT EXISTS `Member`.`Univeristy` (
  `id` INT(11) NOT NULL,
  `name` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB DEFAULT CHARSET=utf8;


-- -----------------------------------------------------
-- Table `Member`.`Major`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Member`.`Major` ;

CREATE TABLE IF NOT EXISTS `Member`.`Major` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `UID` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Major_Univeristy_idx` (`UID` ASC),
  CONSTRAINT `fk_Major_Univeristy`
    FOREIGN KEY (`UID`)
    REFERENCES `Member`.`Univeristy` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB DEFAULT CHARSET=utf8;


-- -----------------------------------------------------
-- Table `Member`.`Grade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Member`.`Grade` ;

CREATE TABLE IF NOT EXISTS `Member`.`Grade` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `MID` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Grade_Major1_idx` (`MID` ASC),
  CONSTRAINT `fk_Grade_Major1`
    FOREIGN KEY (`MID`)
    REFERENCES `Member`.`Major` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB DEFAULT CHARSET=utf8;


-- -----------------------------------------------------
-- Table `Member`.`Coupon`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Member`.`Coupon` ;

CREATE TABLE IF NOT EXISTS `Member`.`Coupon` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `expire_date` VARCHAR(255) NOT NULL,
  `image_path` VARCHAR(255) NOT NULL,
  `UID` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Coupon_Univeristy1_idx` (`UID` ASC),
  CONSTRAINT `fk_Coupon_Univeristy1`
    FOREIGN KEY (`UID`)
    REFERENCES `Member`.`Univeristy` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB DEFAULT CHARSET=utf8;


-- -----------------------------------------------------
-- Table `Member`.`Membership`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Member`.`Membership` ;

CREATE TABLE IF NOT EXISTS `Member`.`Membership` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `member_id` INT(11) NOT NULL,
  `card_num` MEDIUMTEXT NOT NULL,
  `open_id` MEDIUMTEXT NOT NULL,
  `GID` INT(11) NOT NULL,
  `COID` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Membership_Grade1_idx` (`GID` ASC),
  INDEX `fk_Membership_Coupon1_idx` (`COID` ASC),
  CONSTRAINT `fk_Membership_Grade1`
    FOREIGN KEY (`GID`)
    REFERENCES `Member`.`Grade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Membership_Coupon1`
    FOREIGN KEY (`COID`)
    REFERENCES `Member`.`Coupon` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB DEFAULT CHARSET=utf8;


-- -----------------------------------------------------
-- Table `Member`.`Privilege`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Member`.`Privilege` ;

CREATE TABLE IF NOT EXISTS `Member`.`Privilege` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `image_path` VARCHAR(255) NOT NULL,
  `MEID` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Privilege_Membership1_idx` (`MEID` ASC),
  CONSTRAINT `fk_Privilege_Membership1`
    FOREIGN KEY (`MEID`)
    REFERENCES `Member`.`Membership` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB DEFAULT CHARSET=utf8;


-- -----------------------------------------------------
-- Table `Member`.`Administrator`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Member`.`Administrator` ;

CREATE TABLE IF NOT EXISTS `Member`.`Administrator` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `password` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB DEFAULT CHARSET=utf8;


-- -----------------------------------------------------
-- Table `Member`.`BookList`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Member`.`BookList` ;

CREATE TABLE IF NOT EXISTS `Member`.`BookList` (
  `ISBN` MEDIUMTEXT NOT NULL,
  `book_name` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `book_author` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `book_press` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `member_price` INT(11) NOT NULL,
  `original_price` INT(11) NOT NULL,
  PRIMARY KEY (`ISBN`))
ENGINE = InnoDB DEFAULT CHARSET=utf8;


-- -----------------------------------------------------
-- Table `Member`.`Carousel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Member`.`Carousel` ;

CREATE TABLE IF NOT EXISTS `Member`.`Carousel` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `image_path` VARCHAR(255) NOT NULL,
  `UID` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Carousel_Univeristy1_idx` (`UID` ASC),
  CONSTRAINT `fk_Carousel_Univeristy1`
    FOREIGN KEY (`UID`)
    REFERENCES `Member`.`Univeristy` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB DEFAULT CHARSET=utf8;


-- -----------------------------------------------------
-- Table `Member`.`Activity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Member`.`Activity` ;

CREATE TABLE IF NOT EXISTS `Member`.`Activity` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `image_path` VARCHAR(255) NOT NULL,
  `date` VARCHAR(255) NOT NULL,
  `title` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `location` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `UID` INT(11) NOT NULL,
  `MEID` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Activity_Univeristy1_idx` (`UID` ASC),
  INDEX `fk_Activity_Membership1_idx` (`MEID` ASC),
  CONSTRAINT `fk_Activity_Univeristy1`
    FOREIGN KEY (`UID`)
    REFERENCES `Member`.`Univeristy` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Activity_Membership1`
    FOREIGN KEY (`MEID`)
    REFERENCES `Member`.`Membership` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB DEFAULT CHARSET=utf8;


-- -----------------------------------------------------
-- Table `Member`.`Book`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Member`.`Book` ;

CREATE TABLE IF NOT EXISTS `Member`.`Book` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `ISBN` MEDIUMTEXT NOT NULL,
  `name` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `author` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `press` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `member_price` INT(11) NOT NULL,
  `original_price` INT(11) NOT NULL,
  `store_num` INT(11) NOT NULL,
  `image_path` VARCHAR(255) NOT NULL,
  `GID` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Book_Grade1_idx` (`GID` ASC),
  CONSTRAINT `fk_Book_Grade1`
    FOREIGN KEY (`GID`)
    REFERENCES `Member`.`Grade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB DEFAULT CHARSET=utf8;


-- -----------------------------------------------------
-- Table `Member`.`Order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Member`.`Order` ;

CREATE TABLE IF NOT EXISTS `Member`.`Order` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `order_num` MEDIUMTEXT NOT NULL,
  `total_price` INT(11) NOT NULL,
  `shipping_fee` INT(11) NOT NULL,
  `create_date` DATETIME NOT NULL,
  `pay_date` DATETIME NOT NULL,
  `confirm_date` DATETIME NOT NULL,
  `BID` INT(11) NOT NULL,
  `MEID` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Order_Book1_idx` (`BID` ASC),
  INDEX `fk_Order_Membership1_idx` (`MEID` ASC),
  CONSTRAINT `fk_Order_Book1`
    FOREIGN KEY (`BID`)
    REFERENCES `Member`.`Book` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_Membership1`
    FOREIGN KEY (`MEID`)
    REFERENCES `Member`.`Membership` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB DEFAULT CHARSET=utf8;


-- -----------------------------------------------------
-- Table `Member`.`Member_Info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Member`.`Member_Info` ;

CREATE TABLE IF NOT EXISTS `Member`.`Member_Info` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `class_num` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `dorm_num` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `room_num` INT(11) NOT NULL,
  `phone_num` MEDIUMTEXT NOT NULL,
  `Membership_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Member_Info_Membership1_idx` (`Membership_id` ASC),
  CONSTRAINT `fk_Member_Info_Membership1`
    FOREIGN KEY (`Membership_id`)
    REFERENCES `Member`.`Membership` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB DEFAULT CHARSET=utf8; 


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
